FTW: For The Web!

I've have been a developer, for the web, from a long time ago in a
galaxy far far away. In such time, I've developed a number of habitual
programs and libraries.

The outcome is this code, FTW!.

* Gerbil

Most of the code is gerbil. Gerbil is an opinionated dialect of Scheme
designed for Systems Programming, with a state of the art macro and
module system on top of the Gambit runtime.

See https://github.com/vyzo/gerbil.

** Installation

It is available as a ~gxpkg~ from *[[http://github.com/drewc/druix][github.com/drewc/druix]]*.

#+BEGIN_SRC sh
gxpkg install github.com/drewc/ftw
#+END_SRC

Or, if you prefer to hack.

#+BEGIN_SRC sh
gxpkg link github.com/drewc/ftw ~/me/src/ftw/
gxpkg build github.com/drewc/ftw
#+END_SRC

* Common Lisp

A lot of the old code is common lisp. It is in the ~lisp/~ and/or the
~lisp~ branch.  directory. Some of it is still used, and it may still
work wonders.

* License

(C) 2010-2018 Drew Crampsie <me@drewc.ca>

This is free and unencumbered software released into the public domain.

Anyone is free to copy, modify, publish, use, compile, sell, or
distribute this software, either in source code form or as a compiled
binary, for any purpose, commercial or non-commercial, and by any
means.

In jurisdictions that recognize copyright laws, the author or authors
of this software dedicate any and all copyright interest in the
software to the public domain. We make this dedication for the benefit
of the public at large and to the detriment of our heirs and
successors. We intend this dedication to be an overt act of
relinquishment in perpetuity of all present and future rights to this
software under copyright law.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
IN NO EVENT SHALL THE AUTHORS BE LIABLE FOR ANY CLAIM, DAMAGES OR
OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE,
ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
OTHER DEALINGS IN THE SOFTWARE.

For more information, please refer to <http://unlicense.org/>
