(cl:defpackage #:ftw-request-context
  (:nicknames #:ftw-rq)
  (:use :cl :contextl)
  (:export 
   #:context-value
   #:context
   #:request-context
   #:current-request-context
   #:http-method
   #:handle-request
   #:html-stream
   #:parameter-value
   #:map-parameters
   #:request-path
   #:request-path-name
   #:send-redirect
   #:redirect-to
   #:compute-url
   #:url
   
   #:expand-request-context-lamda-list
   #:+http-continue+                        
   #:+http-switching-protocols+           
   #:+http-ok+                            
   #:+http-created+                         
   #:+http-accepted+                        
   #:+http-non-authoritative-information+   
   #:+http-no-content+                      
   #:+http-reset-content+                   
   #:+http-partial-content+                 
   #:+http-multi-status+                    
   #:+http-multiple-choices+                
   #:+http-moved-permanently+               
   #:+http-moved-temporarily+               
   #:+http-see-other+                       
   #:+http-not-modified+                    
   #:+http-use-proxy+                       
   #:+http-temporary-redirect+              
   #:+http-bad-request+                     
   #:+http-authorization-required+          
   #:+http-payment-required+                
   #:+http-forbidden+                       
   #:+http-not-found+                       
   #:+http-method-not-allowed+              
   #:+http-not-acceptable+                  
   #:+http-proxy-authentication-required+   
   #:+http-request-time-out+                
   #:+http-conflict+                        
   #:+http-gone+                            
   #:+http-length-required+                 
   #:+http-precondition-failed+             
   #:+http-request-entity-too-large+        
   #:+http-request-uri-too-large+           
   #:+http-unsupported-media-type+          
   #:+http-requested-range-not-satisfiable+ 
   #:+http-expectation-failed+              
   #:+http-failed-dependency+               
   #:+http-internal-server-error+           
   #:+http-not-implemented+                 
   #:+http-bad-gateway+                     
   #:+http-service-unavailable+             
   #:+http-gateway-time-out+                
   #:+http-version-not-supported+
   #:request-uri
   #:continue-url
   #:context))